name: day_log_flutter
description: Simple diary app.
version: 0.1.0
environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.10.0
  cloud_firestore: ^4.9.0
  firebase_storage: ^11.2.0
  image_picker: ^1.0.7

flutter:
  uses-material-design: true
