name: daylog
description: A new Flutter project for Daylog.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^2.24.0
  firebase_auth: ^4.15.0
  cloud_firestore: ^4.9.2
  firebase_storage: ^11.5.4
  firebase_messaging: ^14.7.10
  flutter_riverpod: ^2.4.9
  google_sign_in: ^5.4.2
  sign_in_with_apple: ^5.0.0
  flutter_facebook_auth: ^6.0.4
  file_picker: ^5.5.0
  image_picker: ^1.0.4
  video_player: ^2.7.2
  just_audio: ^0.9.36
  flutter_quill: ^7.9.6
  flutter_screenutil: ^5.9.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/

